name: Go

on:
  push:
    branches: [ "development", "master"]
  pull_request:
    branches: [ "development", "master"]

jobs:
  gobuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.1

      - name: Linting
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53.3
          args: --verbose

      - name: Build
        run: |
          go build -v

      - name: Test
        run:
          go test -coverprofile=coverage.txt ./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage.txt
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}